### ISSUE TITLE
Azure-Windows-Disk-Encryption Policy edit failure

### ISSUE THREAD

**Issue by nu11modem** [hakashya/Azure-Policy#1]
Hi.  When I open this policy in the portal, it throws an error.  The error is "n.trim is not a function".  I copied the policy from the page below:

https://github.com/hakashya/Azure-Policy/commits/master/Collections/Azure-Windows-Disk-Encryption

thanks!

**Comment by hakashya** [comment]
It is a Portal UI issue, which was caused by the Boolean value in the policy. The fix for the same is developed and will be rolling out within the next 2-3 weeks. 

Meanwhile, you can use other client tools such as PowerShell or REST API to gather the policy definition. You can also edit the policy in the Portal as of now. The only drawback is that you cannot view the policy on the Portal.

**Comment by hakashya** [comment]
The UI issue has been fixed and is not been observed anymore.
